import reflex as rx
from reflexlab.pages.login.login_state import LoginState

@rx.page(route="/loginregistry", title="loginregistry", on_load=LoginState.on_load)
def loginregistry() -> rx.Component:
    return rx.vstack(
        rx.hstack(
            rx.card(
                rx.vstack(
                    rx.center(
                        rx.image(
                            src="/logo.jpg",
                            width="2.5em",
                            height="auto",
                            border_radius="25%",
                        ),
                        rx.heading(
                            "Registro de usuario",
                            size="6",
                            as_="h2",
                            text_align="center",
                            width="100%",
                        ),
                        direction="column",
                        spacing="5",
                        width="100%",
                    ),
                    rx.vstack(
                        rx.text(
                            "Usuario",
                            size="3",
                            weight="medium",
                            text_align="left",
                            width="100%",
                        ),
                        rx.input(
                            placeholder="Su login de usuario",
                            type="text",
                            size="3",
                            width="100%",
                            on_change=LoginState.set_registry_username,
                            value=LoginState.registry_username,
                        ),
                        justify="start",
                        spacing="2",
                        width="100%",
                    ),
                    rx.vstack(
                        rx.hstack(
                            rx.text(
                                "Email",
                                size="3",
                                weight="medium",
                            ),
                            justify="between",
                            width="100%",
                        ),
                        rx.input(
                            placeholder="Email ",
                            type="text",
                            size="3",
                            width="100%",
                            on_change=LoginState.set_registry_email,
                            value=LoginState.registry_email,
                        ),
                        spacing="2",
                        width="100%",
                    ),
                    rx.vstack(
                        rx.hstack(
                            rx.text(
                                "Password",
                                size="3",
                                weight="medium",
                            ),
                            justify="between",
                            width="100%",
                        ),
                        rx.input(
                            placeholder="Password",
                            type="password",
                            size="3",
                            width="100%",
                            on_change=LoginState.set_registry_password,
                            value=LoginState.registry_password,
                        ),
                        spacing="2",
                        width="100%",
                    ),
                    rx.vstack(
                        rx.hstack(
                            rx.text(
                                "Verificar password",
                                size="3",
                                weight="medium",
                            ),
                            justify="between",
                            width="100%",
                        ),
                        rx.input(
                            placeholder="Password",
                            type="password",
                            size="3",
                            width="100%",
                            on_change=LoginState.set_registry_password2,
                            value=LoginState.registry_password2,
                        ),
                        spacing="2",
                        width="100%",
                    ),
                    rx.button(
                        "Registrar usuario",
                        size="3",
                        width="100%",
                        on_click=LoginState.loginregistry,
                    ),
                    rx.cond(
                        LoginState.errlogin != "",
                        rx.hstack(
                            rx.text(
                                LoginState.errlogin,
                                size="3",
                                weight="medium",
                                color="red"
                            ),
                            justify="between",
                            width="100%",
                        ),
                    ),
                    spacing="6",
                    width="100%",
                ),
                size="4",
                max_width="28em",
                width="100%",
            ),
            padding="100px",
            justify="center",
            width="100%",
        ),
    )
